export const styles = {
  page: {
    minHeight: '100dvh',
    backgroundColor: '#f8fafc',
    padding: '24px clamp(16px, 4vw, 32px)',
    boxSizing: 'border-box',
  },
  header: {
    maxWidth: '960px',
    margin: '0 auto 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '16px',
    flexWrap: 'wrap',
  },
  title: {
    display: 'block',
    fontSize: '24px',
    fontWeight: 700,
    color: '#0f172a',
    marginBottom: '8px',
  },
  headerActions: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
  },
  container: {
    maxWidth: '960px',
    margin: '0 auto',
    backgroundColor: '#fff',
    borderRadius: '12px',
    padding: 'clamp(20px, 4vw, 32px)',
    boxShadow: '0 8px 24px rgba(15, 23, 42, 0.06)',
  },
  sectionTitle: {
    display: 'block',
    fontSize: '16px',
    fontWeight: 600,
    color: '#334155',
    marginBottom: '16px',
  },
  summaryRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '20px',
    flexWrap: 'wrap',
  },
  itemCard: {
    marginBottom: '16px',
    border: '1px solid #e2e8f0',
    borderRadius: '10px',
    padding: '16px',
    backgroundColor: '#fafafa',
  },
  itemTitle: {
    display: 'block',
    fontSize: '15px',
    fontWeight: 600,
    color: '#0f172a',
    marginBottom: '12px',
  },
  fieldRow: {
    display: 'flex',
    gap: '8px',
    marginBottom: '10px',
    flexWrap: 'wrap',
  },
  fieldLabel: {
    display: 'block',
    minWidth: '120px',
    fontSize: '14px',
    color: '#64748b',
    flexShrink: 0,
  },
  fieldValue: {
    display: 'block',
    fontSize: '14px',
    color: '#0f172a',
    flex: 1,
    minWidth: 0,
    wordBreak: 'break-word',
  },
  fileLinks: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    flex: 1,
    minWidth: 0,
  },
  fileLink: {
    color: '#2563eb',
    fontSize: '14px',
    wordBreak: 'break-all',
  },
  flagTags: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    marginTop: '4px',
  },
  loadingText: {
    display: 'block',
    color: '#64748b',
    padding: '48px 0',
    textAlign: 'center',
  },
};
