export const styles = {
  page: {
    minHeight: '100dvh',
    backgroundColor: '#f8fafc',
    padding: '24px clamp(16px, 4vw, 32px)',
    boxSizing: 'border-box',
  },
  header: {
    maxWidth: '960px',
    margin: '0 auto 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '16px',
    flexWrap: 'wrap',
  },
  title: {
    display: 'block',
    fontSize: '24px',
    fontWeight: 700,
    color: '#0f172a',
    marginBottom: '8px',
  },
  subtitle: {
    display: 'block',
    fontSize: '14px',
    color: '#64748b',
  },
  headerActions: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
  },
  listCard: {
    maxWidth: '960px',
    margin: '0 auto',
    backgroundColor: '#fff',
    borderRadius: '12px',
    padding: '24px',
    boxShadow: '0 8px 24px rgba(15, 23, 42, 0.06)',
  },
  listTitle: {
    display: 'block',
    fontSize: '18px',
    fontWeight: 600,
    color: '#334155',
    marginBottom: '16px',
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  listItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    padding: '16px',
    borderRadius: '10px',
    border: '1px solid #e2e8f0',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
  },
  listItemMain: {
    flex: 1,
    minWidth: 0,
  },
  listItemTitle: {
    display: 'block',
    fontSize: '15px',
    fontWeight: 600,
    color: '#0f172a',
    marginBottom: '4px',
  },
  listItemMeta: {
    display: 'block',
    fontSize: '13px',
    color: '#64748b',
  },
  emptyText: {
    display: 'block',
    color: '#64748b',
    padding: '24px 0',
    textAlign: 'center',
  },
};
