/**
 * LoginPage 样式
 */

export const styles = {
  loginPage: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    position: 'relative',
    minHeight: '100dvh',
    height: '100dvh',
    padding: 'clamp(16px, 4vw, 40px) clamp(16px, 5vw, 40px)',
    backgroundColor: '#f0f4f8',
    boxSizing: 'border-box',
    overflow: 'auto',
  },
  languageSwitcherContainer: {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 1000,
  },
  loginContainer: {
    width: '100%',
    maxWidth: 'min(calc(100% - 32px), 420px)',
    padding: 'clamp(24px, 5vw, 36px) clamp(20px, 4vw, 28px)',
    backgroundColor: '#fff',
    borderRadius: '12px',
    boxShadow: '0 8px 24px rgba(15, 23, 42, 0.08)',
    boxSizing: 'border-box',
  },
  brandBlock: {
    textAlign: 'center',
    marginBottom: '24px',
  },
  appTitle: {
    fontSize: 'clamp(22px, 5vw, 28px)',
    fontWeight: 700,
    color: '#0f172a',
    display: 'block',
    marginBottom: '8px',
  },
  appSubtitle: {
    fontSize: 'clamp(13px, 3vw, 14px)',
    color: '#64748b',
    display: 'block',
    lineHeight: 1.6,
  },
  roleTabs: {
    display: 'flex',
    gap: '8px',
    marginBottom: '24px',
    padding: '4px',
    backgroundColor: '#f1f5f9',
    borderRadius: '10px',
  },
  roleTab: {
    flex: 1,
    border: 'none',
    borderRadius: '8px',
    padding: '10px 12px',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    backgroundColor: 'transparent',
    color: '#64748b',
    transition: 'all 0.2s ease',
  },
  roleTabActive: {
    backgroundColor: '#fff',
    color: '#1677ff',
    boxShadow: '0 2px 8px rgba(15, 23, 42, 0.08)',
  },
  roleHint: {
    marginBottom: '16px',
    padding: '10px 12px',
    backgroundColor: '#eff6ff',
    border: '1px solid #bfdbfe',
    borderRadius: '8px',
    color: '#1d4ed8',
    fontSize: 'clamp(13px, 3vw, 14px)',
    lineHeight: 1.5,
    display: 'block',
  },
  loginError: {
    marginBottom: '16px',
    padding: 'clamp(8px, 2vw, 12px) clamp(10px, 2vw, 12px)',
    backgroundColor: '#fff2f0',
    border: '1px solid #ffccc7',
    borderRadius: '8px',
    color: '#ff4d4f',
    fontSize: 'clamp(13px, 3vw, 14px)',
  },
  errorText: {
    color: '#ff4d4f',
  },
};
